version: '3.8'

services:
  db:
    image: mysql:8
    hostname: db
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=mastedatabasen_sites
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_pwd
      - MYSQL_USER=mastedatabasen_user
      - MYSQL_PASSWORD=mastedatabasen
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - mysql_root_pwd

  # node:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.api
  #   depends_on:
  #     - db
  #   cap_add:
  #     - SYS_NICE
  #   restart: always
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=3306
  #     - DB_DATABASE=mastedatabasen_sites
  #     - DB_USER=mastedatabasen_user
  #     - DB_PASSWORD=mastedatabasen
  #     - PORT=8080
  #   ports:
  #     - '8080:8080'

  node-dev:
    build:
      context: .
      dockerfile: Dockerfile.api.dev
    depends_on:
      - db
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=mastedatabasen_sites
      - DB_USER=mastedatabasen_user
      - DB_PASSWORD=mastedatabasen
      - PORT=8080
    ports:
      - '8080:8080'
    volumes:
      - ./api:/usr/src/app

volumes:
  db:


secrets:
  mysql_root_pwd:
    file: ./mysql_root_pwd.txt
