version: "3.8"

services:
  db:
    image: mysql:8
    hostname: db
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=mastedatabasen_sites
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_pwd
      - MYSQL_USER=mastedatabasen_user
      - MYSQL_PASSWORD=mastedatabasen
    ports:
      - "3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - mysql_root_pwd
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 50

  node:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - api.env
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=mastedatabasen_sites
      - DB_USER=mastedatabasen_user
      - DB_PASSWORD=mastedatabasen
      - PORT=8080
    ports:
      - "8080:8080"

  # node-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.api.dev
  #   depends_on:
  #     - db
  #   restart: always
  #   env_file:
  #     - api.env
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=3306
  #     - DB_DATABASE=mastedatabasen_sites
  #     - DB_USER=mastedatabasen_user
  #     - DB_PASSWORD=mastedatabasen
  #     - PORT=8080
  #   ports:
  #     - '8080:8080'
  #   volumes:
  #     - ./api:/usr/src/app

volumes:
  db:

secrets:
  mysql_root_pwd:
    file: ./mysql_root_pwd.txt
