version: '3.8'

services:
  db:
    image: mysql:8
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=mastedatabasen_sites
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_pwd
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - mysql_root_pwd

volumes:
  db:


secrets:
  mysql_root_pwd:
    file: ./mysql_root_pwd.txt
