# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Generate sites SQL dump

on:
  workflow_dispatch:
  schedule:
    # Set up to run a day after the scraper auto-runs
    - cron: "0 12 * * 2"

permissions:
  contents: read

jobs:
  build:
    name: Create SQL dump

    # Self-hosted runners get longer job time limits
    runs-on: [self-hosted, Linux]

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    env:
      MYSQL_PWD: "MY_SECURE_PASSW0RD!"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Spin up API Docker containers
        run: |
          echo $MYSQL_PWD > mysql_root_pwd.txt
          cp api.env.example api.env
          sed -i -e "s/- '3306'/- '3306:3306'/" ./docker-compose.yml
          docker compose up -d

      - name: Import sites to database
        run: |
          wget https://raw.githubusercontent.com/davwheat/mastedatabasen-dk-scraper/main/sites_current_with_operator.json
          python ./import_mastedatabase_dump.py

      - name: Generate SQL dump
        run: |
          mysqldump -u root -p"${MYSQL_PWD}" mastedatabasen_sites -h 127.0.0.1 > "./dumps/mastedatabasen_sites-$(date +"%Y-%m-%d").sql"

      - name: Spin down API Docker containers
        run: |
          docker compose down

      - name: Clean up local repository state
        run: |
          rm api.env
          rm sites_current_with_operator.json
          git checkout -- docker-compose.yml

      - name: Commit and push SQL dump
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add updated sites SQL dump
          branch: main
          file_pattern: 'dumps/*.sql'
